-- 도서
CREATE TABLE "MY_SCHEMA"."BOOKS" (
	"BOOK_ID"          NUMBER(10)     NOT NULL, -- 도서번호
	"ISBN"             VARCHAR2(15)   NOT NULL, -- ISBN
	"BOOK_NAME"        VARCHAR2(30)   NOT NULL, -- 도서이름
	"PUBLICATION_DATE" DATE           NOT NULL, -- 출간일
	"PAGE"             NUMBER(4)      NOT NULL, -- 페이지
	"LIST_PRICE"       NUMBER(10)     NOT NULL, -- 정가
	"SALE_PRICE"       NUMBER(10)     NOT NULL, -- 판매가
	"REWARD_POINT"     NUMBER(5)      NOT NULL, -- 적립금
	"TAX_DEDUCTION_YN" NUMBER(1)      NOT NULL, -- 소득공제
	"PUBLISHER_NAME"   VARCHAR2(30)   NOT NULL, -- 출판사
	"AUTHER_NAME"      VARCHAR2(30)   NOT NULL, -- 저자
	"BOOK_SIZE"        VARCHAR2(15)   NOT NULL, -- 판형
	"IMAGE_URL"        VARCHAR2(4000) NULL,     -- 이미지
	"CATEGORY_ID"      NUMBER(4)      NOT NULL  -- 카테고리아이디
);

-- 도서 기본키
CREATE UNIQUE INDEX "MY_SCHEMA"."PK_BOOKS"
	ON "MY_SCHEMA"."BOOKS" ( -- 도서
		"BOOK_ID" ASC -- 도서번호
	);

-- 도서
ALTER TABLE "MY_SCHEMA"."BOOKS"
	ADD
		CONSTRAINT "PK_BOOKS" -- 도서 기본키
		PRIMARY KEY (
			"BOOK_ID" -- 도서번호
		);

-- 도서
COMMENT ON TABLE "MY_SCHEMA"."BOOKS" IS '도서';

-- 도서번호
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."BOOK_ID" IS '도서번호';

-- ISBN
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."ISBN" IS 'ISBN';

-- 도서이름
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."BOOK_NAME" IS '도서이름';

-- 출간일
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."PUBLICATION_DATE" IS '출간일';

-- 페이지
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."PAGE" IS '페이지';

-- 정가
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."LIST_PRICE" IS '정가';

-- 판매가
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."SALE_PRICE" IS '판매가';

-- 적립금
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."REWARD_POINT" IS '적립금';

-- 소득공제
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."TAX_DEDUCTION_YN" IS '0/1';

-- 출판사
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."PUBLISHER_NAME" IS '출판사';

-- 저자
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."AUTHER_NAME" IS '저자';

-- 판형
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."BOOK_SIZE" IS '판형';

-- 이미지
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."IMAGE_URL" IS '이미지';

-- 카테고리아이디
COMMENT ON COLUMN "MY_SCHEMA"."BOOKS"."CATEGORY_ID" IS '카테고리아이디';

-- 도서 기본키
COMMENT ON INDEX "MY_SCHEMA"."PK_BOOKS" IS '도서 기본키';

-- 도서 기본키
COMMENT ON CONSTRAINT "MY_SCHEMA"."BOOKS"."PK_BOOKS" IS '도서 기본키';

-- 결제수단
CREATE TABLE "MY_SCHEMA"."PAYMENT_METHODS" (
	"ORDER_ID"     NUMBER(4)    NOT NULL, -- 주문번호
	"PAYMENT_TYPE" VARCHAR2(15) NOT NULL  -- 수단
);

-- 결제수단
COMMENT ON TABLE "MY_SCHEMA"."PAYMENT_METHODS" IS '결제수단';

-- 주문번호
COMMENT ON COLUMN "MY_SCHEMA"."PAYMENT_METHODS"."ORDER_ID" IS '주문번호';

-- 수단
COMMENT ON COLUMN "MY_SCHEMA"."PAYMENT_METHODS"."PAYMENT_TYPE" IS '수단';

-- 연령등급
CREATE TABLE "MY_SCHEMA"."AGE_RATINGS" (
	"AGE_RATING_ID" NUMBER(4)    NOT NULL, -- 연령등급아이디
	"RATING_NAME"   VARCHAR2(15) NOT NULL  -- 등급
);

-- 연령등급 기본키
CREATE UNIQUE INDEX "MY_SCHEMA"."PK_AGE_RATINGS"
	ON "MY_SCHEMA"."AGE_RATINGS" ( -- 연령등급
		"AGE_RATING_ID" ASC -- 연령등급아이디
	);

-- 연령등급
ALTER TABLE "MY_SCHEMA"."AGE_RATINGS"
	ADD
		CONSTRAINT "PK_AGE_RATINGS" -- 연령등급 기본키
		PRIMARY KEY (
			"AGE_RATING_ID" -- 연령등급아이디
		);

-- 연령등급
COMMENT ON TABLE "MY_SCHEMA"."AGE_RATINGS" IS '연령등급';

-- 연령등급아이디
COMMENT ON COLUMN "MY_SCHEMA"."AGE_RATINGS"."AGE_RATING_ID" IS '연령등급아이디';

-- 등급
COMMENT ON COLUMN "MY_SCHEMA"."AGE_RATINGS"."RATING_NAME" IS '등급';

-- 연령등급 기본키
COMMENT ON INDEX "MY_SCHEMA"."PK_AGE_RATINGS" IS '연령등급 기본키';

-- 연령등급 기본키
COMMENT ON CONSTRAINT "MY_SCHEMA"."AGE_RATINGS"."PK_AGE_RATINGS" IS '연령등급 기본키';

-- 배송정보
CREATE TABLE "MY_SCHEMA"."DELIVERY_ADDRESSES" (
	"DELIVERY_ADDRESS_ID" NUMBER(4)      NOT NULL, -- 배송지아이디
	"POSTAL_CODE"         VARCHAR2(10)   NOT NULL, -- 우편번호
	"BASE_ADDRESS"        VARCHAR2(100)  NOT NULL, -- 주소
	"DETAIL_ADDRESS"      VARCHAR2(100)  NOT NULL, -- 상세주소
	"DELIVERY_REQUEST"    VARCHAR2(5000) NOT NULL, -- 배송요청사항
	"MOBILE_NUMBER"       VARCHAR2(15)   NOT NULL, -- 휴대전화번호
	"PHONE_NUMBER"        VARCHAR2(15)   NULL      -- 전화번호
);

-- 배송정보 기본키
CREATE UNIQUE INDEX "MY_SCHEMA"."PK_DELIVERY_ADDRESSES"
	ON "MY_SCHEMA"."DELIVERY_ADDRESSES" ( -- 배송정보
		"DELIVERY_ADDRESS_ID" ASC -- 배송지아이디
	);

-- 배송정보
ALTER TABLE "MY_SCHEMA"."DELIVERY_ADDRESSES"
	ADD
		CONSTRAINT "PK_DELIVERY_ADDRESSES" -- 배송정보 기본키
		PRIMARY KEY (
			"DELIVERY_ADDRESS_ID" -- 배송지아이디
		);

-- 배송정보
COMMENT ON TABLE "MY_SCHEMA"."DELIVERY_ADDRESSES" IS '배송정보';

-- 배송지아이디
COMMENT ON COLUMN "MY_SCHEMA"."DELIVERY_ADDRESSES"."DELIVERY_ADDRESS_ID" IS '배송지아이디';

-- 우편번호
COMMENT ON COLUMN "MY_SCHEMA"."DELIVERY_ADDRESSES"."POSTAL_CODE" IS '우편번호';

-- 주소
COMMENT ON COLUMN "MY_SCHEMA"."DELIVERY_ADDRESSES"."BASE_ADDRESS" IS '주소';

-- 상세주소
COMMENT ON COLUMN "MY_SCHEMA"."DELIVERY_ADDRESSES"."DETAIL_ADDRESS" IS '상세주소';

-- 배송요청사항
COMMENT ON COLUMN "MY_SCHEMA"."DELIVERY_ADDRESSES"."DELIVERY_REQUEST" IS '배송요청사항';

-- 휴대전화번호
COMMENT ON COLUMN "MY_SCHEMA"."DELIVERY_ADDRESSES"."MOBILE_NUMBER" IS '휴대전화번호';

-- 전화번호
COMMENT ON COLUMN "MY_SCHEMA"."DELIVERY_ADDRESSES"."PHONE_NUMBER" IS '전화번호';

-- 배송정보 기본키
COMMENT ON INDEX "MY_SCHEMA"."PK_DELIVERY_ADDRESSES" IS '배송정보 기본키';

-- 배송정보 기본키
COMMENT ON CONSTRAINT "MY_SCHEMA"."DELIVERY_ADDRESSES"."PK_DELIVERY_ADDRESSES" IS '배송정보 기본키';

-- 자녀
CREATE TABLE "MY_SCHEMA"."CHILDREN" (
	"CHILD_ID"   NUMBER(4)  NOT NULL, -- 자녀번호
	"MEMBER_ID"  NUMBER(10) NOT NULL, -- 회원번호
	"BIRTH_DATE" DATE       NOT NULL  -- 생년월일
);

-- 자녀 기본키
CREATE UNIQUE INDEX "MY_SCHEMA"."PK_CHILDREN"
	ON "MY_SCHEMA"."CHILDREN" ( -- 자녀
		"CHILD_ID" ASC -- 자녀번호
	);

-- 자녀
ALTER TABLE "MY_SCHEMA"."CHILDREN"
	ADD
		CONSTRAINT "PK_CHILDREN" -- 자녀 기본키
		PRIMARY KEY (
			"CHILD_ID" -- 자녀번호
		);

-- 자녀
COMMENT ON TABLE "MY_SCHEMA"."CHILDREN" IS '자녀';

-- 자녀번호
COMMENT ON COLUMN "MY_SCHEMA"."CHILDREN"."CHILD_ID" IS '자녀번호';

-- 회원번호
COMMENT ON COLUMN "MY_SCHEMA"."CHILDREN"."MEMBER_ID" IS '회원번호';

-- 생년월일
COMMENT ON COLUMN "MY_SCHEMA"."CHILDREN"."BIRTH_DATE" IS '생년월일';

-- 자녀 기본키
COMMENT ON INDEX "MY_SCHEMA"."PK_CHILDREN" IS '자녀 기본키';

-- 자녀 기본키
COMMENT ON CONSTRAINT "MY_SCHEMA"."CHILDREN"."PK_CHILDREN" IS '자녀 기본키';

-- 장바구니
CREATE TABLE "MY_SCHEMA"."CART_ITEMS" (
	"MEMBER_ID" NUMBER(10)   NOT NULL, -- 회원번호
	"BOOK_ID"   NUMBER(10)   NOT NULL, -- 도서번호
	"QUANTITY"  NUMBER(3)    NOT NULL, -- 수량
	"BOOK_NAME" VARCHAR2(15) NOT NULL, -- 도서명
	"PRICE"     NUMBER(10)   NOT NULL  -- 가격
);

-- 장바구니 기본키
CREATE UNIQUE INDEX "MY_SCHEMA"."PK_CART_ITEMS"
	ON "MY_SCHEMA"."CART_ITEMS" ( -- 장바구니
		"MEMBER_ID" ASC, -- 회원번호
		"BOOK_ID"   ASC  -- 도서번호
	);

-- 장바구니
ALTER TABLE "MY_SCHEMA"."CART_ITEMS"
	ADD
		CONSTRAINT "PK_CART_ITEMS" -- 장바구니 기본키
		PRIMARY KEY (
			"MEMBER_ID", -- 회원번호
			"BOOK_ID"    -- 도서번호
		);

-- 장바구니
COMMENT ON TABLE "MY_SCHEMA"."CART_ITEMS" IS '장바구니';

-- 회원번호
COMMENT ON COLUMN "MY_SCHEMA"."CART_ITEMS"."MEMBER_ID" IS '회원번호';

-- 도서번호
COMMENT ON COLUMN "MY_SCHEMA"."CART_ITEMS"."BOOK_ID" IS '도서번호';

-- 수량
COMMENT ON COLUMN "MY_SCHEMA"."CART_ITEMS"."QUANTITY" IS '수량';

-- 도서명
COMMENT ON COLUMN "MY_SCHEMA"."CART_ITEMS"."BOOK_NAME" IS '도서명';

-- 가격
COMMENT ON COLUMN "MY_SCHEMA"."CART_ITEMS"."PRICE" IS '가격';

-- 장바구니 기본키
COMMENT ON INDEX "MY_SCHEMA"."PK_CART_ITEMS" IS '장바구니 기본키';

-- 장바구니 기본키
COMMENT ON CONSTRAINT "MY_SCHEMA"."CART_ITEMS"."PK_CART_ITEMS" IS '장바구니 기본키';

-- 주문
CREATE TABLE "MY_SCHEMA"."ORDERS" (
	"ORDER_ID"            NUMBER(4)  NOT NULL, -- 주문번호
	"BOOK_ID"             NUMBER(10) NOT NULL, -- 도서번호
	"MEMBER_ID"           NUMBER(10) NOT NULL, -- 회원번호
	"DELIVERY_ADDRESS_ID" NUMBER(4)  NOT NULL, -- 배송지아이디
	"DELIVERY_FEE"        NUMBER(4)  NOT NULL, -- 배송비
	"QUANTITY"            NUMBER(3)  NOT NULL, -- 수량
	"PAYMENT_AMOUNT"      NUMBER(10) NOT NULL  -- 결제금액
);

-- 주문 기본키
CREATE UNIQUE INDEX "MY_SCHEMA"."PK_ORDERS"
	ON "MY_SCHEMA"."ORDERS" ( -- 주문
		"ORDER_ID" ASC -- 주문번호
	);

-- 주문
ALTER TABLE "MY_SCHEMA"."ORDERS"
	ADD
		CONSTRAINT "PK_ORDERS" -- 주문 기본키
		PRIMARY KEY (
			"ORDER_ID" -- 주문번호
		);

-- 주문
COMMENT ON TABLE "MY_SCHEMA"."ORDERS" IS '주문';

-- 주문번호
COMMENT ON COLUMN "MY_SCHEMA"."ORDERS"."ORDER_ID" IS '주문번호';

-- 도서번호
COMMENT ON COLUMN "MY_SCHEMA"."ORDERS"."BOOK_ID" IS '도서번호';

-- 회원번호
COMMENT ON COLUMN "MY_SCHEMA"."ORDERS"."MEMBER_ID" IS '회원번호';

-- 배송지아이디
COMMENT ON COLUMN "MY_SCHEMA"."ORDERS"."DELIVERY_ADDRESS_ID" IS '배송지아이디';

-- 배송비
COMMENT ON COLUMN "MY_SCHEMA"."ORDERS"."DELIVERY_FEE" IS '배송비';

-- 수량
COMMENT ON COLUMN "MY_SCHEMA"."ORDERS"."QUANTITY" IS '수량';

-- 결제금액
COMMENT ON COLUMN "MY_SCHEMA"."ORDERS"."PAYMENT_AMOUNT" IS '결제금액';

-- 주문 기본키
COMMENT ON INDEX "MY_SCHEMA"."PK_ORDERS" IS '주문 기본키';

-- 주문 기본키
COMMENT ON CONSTRAINT "MY_SCHEMA"."ORDERS"."PK_ORDERS" IS '주문 기본키';

-- 카테고리
CREATE TABLE "MY_SCHEMA"."CATEGORIES" (
	"CATEGORY_ID"   NUMBER(4)    NOT NULL, -- 카테고리아이디
	"AGE_RATING_ID" NUMBER(4)    NOT NULL, -- 연령등급아이디
	"CATEGORY_NAME" VARCHAR2(15) NOT NULL  -- 분류
);

-- 카테고리 기본키
CREATE UNIQUE INDEX "MY_SCHEMA"."PK_CATEGORIES"
	ON "MY_SCHEMA"."CATEGORIES" ( -- 카테고리
		"CATEGORY_ID" ASC -- 카테고리아이디
	);

-- 카테고리
ALTER TABLE "MY_SCHEMA"."CATEGORIES"
	ADD
		CONSTRAINT "PK_CATEGORIES" -- 카테고리 기본키
		PRIMARY KEY (
			"CATEGORY_ID" -- 카테고리아이디
		);

-- 카테고리
COMMENT ON TABLE "MY_SCHEMA"."CATEGORIES" IS '카테고리';

-- 카테고리아이디
COMMENT ON COLUMN "MY_SCHEMA"."CATEGORIES"."CATEGORY_ID" IS '카테고리아이디';

-- 연령등급아이디
COMMENT ON COLUMN "MY_SCHEMA"."CATEGORIES"."AGE_RATING_ID" IS '연령등급아이디';

-- 분류
COMMENT ON COLUMN "MY_SCHEMA"."CATEGORIES"."CATEGORY_NAME" IS '분류';

-- 카테고리 기본키
COMMENT ON INDEX "MY_SCHEMA"."PK_CATEGORIES" IS '카테고리 기본키';

-- 카테고리 기본키
COMMENT ON CONSTRAINT "MY_SCHEMA"."CATEGORIES"."PK_CATEGORIES" IS '카테고리 기본키';

-- 주소
CREATE TABLE "MY_SCHEMA"."ADDRESSES" (
	"ADDRESS_ID"     NUMBER(4)     NOT NULL, -- 주소아이디
	"POSTAL_CODE"    VARCHAR2(10)  NOT NULL, -- 우편번호
	"BASE_ADDRESS"   VARCHAR2(100) NOT NULL, -- 주소
	"DETAIL_ADDRESS" VARCHAR2(100) NOT NULL, -- 상세주소
	"MEMBER_ID"      NUMBER(10)    NOT NULL, -- 회원번호
	"ADDRESS_ID2"    NUMBER(4)     NULL      -- 주소아이디2
);

-- 주소 기본키
CREATE UNIQUE INDEX "MY_SCHEMA"."PK_ADDRESSES"
	ON "MY_SCHEMA"."ADDRESSES" ( -- 주소
		"ADDRESS_ID" ASC -- 주소아이디
	);

-- 주소
ALTER TABLE "MY_SCHEMA"."ADDRESSES"
	ADD
		CONSTRAINT "PK_ADDRESSES" -- 주소 기본키
		PRIMARY KEY (
			"ADDRESS_ID" -- 주소아이디
		);

-- 주소
COMMENT ON TABLE "MY_SCHEMA"."ADDRESSES" IS '주소';

-- 주소아이디
COMMENT ON COLUMN "MY_SCHEMA"."ADDRESSES"."ADDRESS_ID" IS '주소아이디';

-- 우편번호
COMMENT ON COLUMN "MY_SCHEMA"."ADDRESSES"."POSTAL_CODE" IS '우편번호';

-- 주소
COMMENT ON COLUMN "MY_SCHEMA"."ADDRESSES"."BASE_ADDRESS" IS '주소';

-- 상세주소
COMMENT ON COLUMN "MY_SCHEMA"."ADDRESSES"."DETAIL_ADDRESS" IS '상세주소';

-- 회원번호
COMMENT ON COLUMN "MY_SCHEMA"."ADDRESSES"."MEMBER_ID" IS '회원번호';

-- 주소아이디2
COMMENT ON COLUMN "MY_SCHEMA"."ADDRESSES"."ADDRESS_ID2" IS '주소아이디2';

-- 주소 기본키
COMMENT ON INDEX "MY_SCHEMA"."PK_ADDRESSES" IS '주소 기본키';

-- 주소 기본키
COMMENT ON CONSTRAINT "MY_SCHEMA"."ADDRESSES"."PK_ADDRESSES" IS '주소 기본키';

-- 회원
CREATE TABLE "MY_SCHEMA"."MEMBER" (
	"MEMBER_ID"       NUMBER(10)   NOT NULL, -- 회원번호
	"MEMBER_LOGIN_ID" VARCHAR2(15) NOT NULL, -- 회원아이디
	"PASSWORD"        VARCHAR2(20) NOT NULL, -- 비밀번호
	"MEMBER_NAME"     VARCHAR2(20) NOT NULL, -- 회원이름
	"SEX"             NUMBER(1)    NOT NULL, -- 성별
	"PHONE_NUBER"     VARCHAR2(20) NOT NULL, -- 전화번호
	"BIRTH_DATE"      DATE         NOT NULL, -- 생년월일
	"EMAIL"           VARCHAR2(30) NOT NULL, -- 이메일
	"HAS_CHILDREN"    NUMBER(1)    NOT NULL  -- 자녀 여부
);

-- 회원 기본키
CREATE UNIQUE INDEX "MY_SCHEMA"."PK_MEMBER"
	ON "MY_SCHEMA"."MEMBER" ( -- 회원
		"MEMBER_ID" ASC -- 회원번호
	);

-- 회원
ALTER TABLE "MY_SCHEMA"."MEMBER"
	ADD
		CONSTRAINT "PK_MEMBER" -- 회원 기본키
		PRIMARY KEY (
			"MEMBER_ID" -- 회원번호
		);

-- 회원
COMMENT ON TABLE "MY_SCHEMA"."MEMBER" IS '회원';

-- 회원번호
COMMENT ON COLUMN "MY_SCHEMA"."MEMBER"."MEMBER_ID" IS 'sequence';

-- 회원아이디
COMMENT ON COLUMN "MY_SCHEMA"."MEMBER"."MEMBER_LOGIN_ID" IS '회원아이디';

-- 비밀번호
COMMENT ON COLUMN "MY_SCHEMA"."MEMBER"."PASSWORD" IS '비밀번호';

-- 회원이름
COMMENT ON COLUMN "MY_SCHEMA"."MEMBER"."MEMBER_NAME" IS '회원이름';

-- 성별
COMMENT ON COLUMN "MY_SCHEMA"."MEMBER"."SEX" IS '0/1';

-- 전화번호
COMMENT ON COLUMN "MY_SCHEMA"."MEMBER"."PHONE_NUBER" IS '전화번호';

-- 생년월일
COMMENT ON COLUMN "MY_SCHEMA"."MEMBER"."BIRTH_DATE" IS '생년월일';

-- 이메일
COMMENT ON COLUMN "MY_SCHEMA"."MEMBER"."EMAIL" IS '이메일';

-- 자녀 여부
COMMENT ON COLUMN "MY_SCHEMA"."MEMBER"."HAS_CHILDREN" IS 'default(0)';

-- 회원 기본키
COMMENT ON INDEX "MY_SCHEMA"."PK_MEMBER" IS '회원 기본키';

-- 회원 기본키
COMMENT ON CONSTRAINT "MY_SCHEMA"."MEMBER"."PK_MEMBER" IS '회원 기본키';

-- 회원 종류
CREATE TABLE "MY_SCHEMA"."MEMBER_TYPE" (
	"MEMBER_ID"        NUMBER(10)  NOT NULL, -- 회원번호
	"MEMBER_TYPE_CODE" VARCHAR2(7) NOT NULL  -- 구분
);

-- 회원 종류
COMMENT ON TABLE "MY_SCHEMA"."MEMBER_TYPE" IS '회원 종류';

-- 회원번호
COMMENT ON COLUMN "MY_SCHEMA"."MEMBER_TYPE"."MEMBER_ID" IS '회원번호';

-- 구분
COMMENT ON COLUMN "MY_SCHEMA"."MEMBER_TYPE"."MEMBER_TYPE_CODE" IS '구분';

-- 도서
ALTER TABLE "MY_SCHEMA"."BOOKS"
	ADD
		CONSTRAINT "FK_CATEGORIES_TO_BOOKS" -- 카테고리 -> 도서
		FOREIGN KEY (
			"CATEGORY_ID" -- 카테고리아이디
		)
		REFERENCES "MY_SCHEMA"."CATEGORIES" ( -- 카테고리
			"CATEGORY_ID" -- 카테고리아이디
		);

-- 카테고리 -> 도서
COMMENT ON CONSTRAINT "MY_SCHEMA"."BOOKS"."FK_CATEGORIES_TO_BOOKS" IS '카테고리 -> 도서';

-- 결제수단
ALTER TABLE "MY_SCHEMA"."PAYMENT_METHODS"
	ADD
		CONSTRAINT "FK_ORDERS_TO_PAYMENT_METHODS" -- 주문 -> 결제수단
		FOREIGN KEY (
			"ORDER_ID" -- 주문번호
		)
		REFERENCES "MY_SCHEMA"."ORDERS" ( -- 주문
			"ORDER_ID" -- 주문번호
		);

-- 주문 -> 결제수단
COMMENT ON CONSTRAINT "MY_SCHEMA"."PAYMENT_METHODS"."FK_ORDERS_TO_PAYMENT_METHODS" IS '주문 -> 결제수단';

-- 자녀
ALTER TABLE "MY_SCHEMA"."CHILDREN"
	ADD
		CONSTRAINT "FK_MEMBER_TO_CHILDREN" -- 회원 -> 자녀
		FOREIGN KEY (
			"MEMBER_ID" -- 회원번호
		)
		REFERENCES "MY_SCHEMA"."MEMBER" ( -- 회원
			"MEMBER_ID" -- 회원번호
		);

-- 회원 -> 자녀
COMMENT ON CONSTRAINT "MY_SCHEMA"."CHILDREN"."FK_MEMBER_TO_CHILDREN" IS '회원 -> 자녀';

-- 장바구니
ALTER TABLE "MY_SCHEMA"."CART_ITEMS"
	ADD
		CONSTRAINT "FK_MEMBER_TO_CART_ITEMS" -- 회원 -> 장바구니
		FOREIGN KEY (
			"MEMBER_ID" -- 회원번호
		)
		REFERENCES "MY_SCHEMA"."MEMBER" ( -- 회원
			"MEMBER_ID" -- 회원번호
		);

-- 회원 -> 장바구니
COMMENT ON CONSTRAINT "MY_SCHEMA"."CART_ITEMS"."FK_MEMBER_TO_CART_ITEMS" IS '회원 -> 장바구니';

-- 장바구니
ALTER TABLE "MY_SCHEMA"."CART_ITEMS"
	ADD
		CONSTRAINT "FK_BOOKS_TO_CART_ITEMS" -- 도서 -> 장바구니
		FOREIGN KEY (
			"BOOK_ID" -- 도서번호
		)
		REFERENCES "MY_SCHEMA"."BOOKS" ( -- 도서
			"BOOK_ID" -- 도서번호
		);

-- 도서 -> 장바구니
COMMENT ON CONSTRAINT "MY_SCHEMA"."CART_ITEMS"."FK_BOOKS_TO_CART_ITEMS" IS '도서 -> 장바구니';

-- 주문
ALTER TABLE "MY_SCHEMA"."ORDERS"
	ADD
		CONSTRAINT "FK_BOOKS_TO_ORDERS" -- 도서 -> 주문
		FOREIGN KEY (
			"BOOK_ID" -- 도서번호
		)
		REFERENCES "MY_SCHEMA"."BOOKS" ( -- 도서
			"BOOK_ID" -- 도서번호
		);

-- 도서 -> 주문
COMMENT ON CONSTRAINT "MY_SCHEMA"."ORDERS"."FK_BOOKS_TO_ORDERS" IS '도서 -> 주문';

-- 주문
ALTER TABLE "MY_SCHEMA"."ORDERS"
	ADD
		CONSTRAINT "FK_MEMBER_TO_ORDERS" -- 회원 -> 주문
		FOREIGN KEY (
			"MEMBER_ID" -- 회원번호
		)
		REFERENCES "MY_SCHEMA"."MEMBER" ( -- 회원
			"MEMBER_ID" -- 회원번호
		);

-- 회원 -> 주문
COMMENT ON CONSTRAINT "MY_SCHEMA"."ORDERS"."FK_MEMBER_TO_ORDERS" IS '회원 -> 주문';

-- 주문
ALTER TABLE "MY_SCHEMA"."ORDERS"
	ADD
		CONSTRAINT "FK_DELIVERY_ADDRESSES_TO_ORDERS" -- 배송정보 -> 주문
		FOREIGN KEY (
			"DELIVERY_ADDRESS_ID" -- 배송지아이디
		)
		REFERENCES "MY_SCHEMA"."DELIVERY_ADDRESSES" ( -- 배송정보
			"DELIVERY_ADDRESS_ID" -- 배송지아이디
		);

-- 배송정보 -> 주문
COMMENT ON CONSTRAINT "MY_SCHEMA"."ORDERS"."FK_DELIVERY_ADDRESSES_TO_ORDERS" IS '배송정보 -> 주문';

-- 카테고리
ALTER TABLE "MY_SCHEMA"."CATEGORIES"
	ADD
		CONSTRAINT "FK_AGE_RATINGS_TO_CATEGORIES" -- 연령등급 -> 카테고리
		FOREIGN KEY (
			"AGE_RATING_ID" -- 연령등급아이디
		)
		REFERENCES "MY_SCHEMA"."AGE_RATINGS" ( -- 연령등급
			"AGE_RATING_ID" -- 연령등급아이디
		);

-- 연령등급 -> 카테고리
COMMENT ON CONSTRAINT "MY_SCHEMA"."CATEGORIES"."FK_AGE_RATINGS_TO_CATEGORIES" IS '연령등급 -> 카테고리';

-- 주소
ALTER TABLE "MY_SCHEMA"."ADDRESSES"
	ADD
		CONSTRAINT "FK_MEMBER_TO_ADDRESSES" -- 회원 -> 주소
		FOREIGN KEY (
			"MEMBER_ID" -- 회원번호
		)
		REFERENCES "MY_SCHEMA"."MEMBER" ( -- 회원
			"MEMBER_ID" -- 회원번호
		);

-- 회원 -> 주소
COMMENT ON CONSTRAINT "MY_SCHEMA"."ADDRESSES"."FK_MEMBER_TO_ADDRESSES" IS '회원 -> 주소';

-- 주소
ALTER TABLE "MY_SCHEMA"."ADDRESSES"
	ADD
		CONSTRAINT "FK_ADDRESSES_TO_ADDRESSES" -- 주소 -> 주소
		FOREIGN KEY (
			"ADDRESS_ID2" -- 주소아이디2
		)
		REFERENCES "MY_SCHEMA"."ADDRESSES" ( -- 주소
			"ADDRESS_ID" -- 주소아이디
		);

-- 주소 -> 주소
COMMENT ON CONSTRAINT "MY_SCHEMA"."ADDRESSES"."FK_ADDRESSES_TO_ADDRESSES" IS '주소 -> 주소';

-- 회원 종류
ALTER TABLE "MY_SCHEMA"."MEMBER_TYPE"
	ADD
		CONSTRAINT "FK_MEMBER_TO_MEMBER_TYPE" -- 회원 -> 회원 종류
		FOREIGN KEY (
			"MEMBER_ID" -- 회원번호
		)
		REFERENCES "MY_SCHEMA"."MEMBER" ( -- 회원
			"MEMBER_ID" -- 회원번호
		);

-- 회원 -> 회원 종류
COMMENT ON CONSTRAINT "MY_SCHEMA"."MEMBER_TYPE"."FK_MEMBER_TO_MEMBER_TYPE" IS '회원 -> 회원 종류';