-- 트리거 삭제
DROP TRIGGER TRG_AGE_RATING_ID;
DROP TRIGGER TRG_CATEGORY_ID;
DROP TRIGGER TRG_BOOK_ID;
DROP TRIGGER TRG_MEMBER_ID;
DROP TRIGGER TRG_CHILD_ID;
DROP TRIGGER TRG_ADDRESS_ID;
DROP TRIGGER TRG_DELIVERY_ADDRESS_ID;
DROP TRIGGER TRG_ORDER_ID;
DROP TRIGGER TRG_PAYMENT_ID;
DROP TRIGGER TRG_DELETE_MEMBER;
DROP TRIGGER TRG_SYNC_CART_ITEMS;

DROP TABLE "BOOKS" cascade constraint;
DROP TABLE "PAYMENT_METHODS" cascade constraint;
DROP TABLE "AGE_RATINGS" cascade constraint;
DROP TABLE "DELIVERY_ADDRESSES" cascade constraint;
DROP TABLE "CHILDREN";
DROP TABLE "CART_ITEMS";
DROP TABLE "ORDERS";
DROP TABLE "CATEGORIES" cascade constraint;
DROP TABLE "ADDRESSES";
DROP TABLE "MEMBER" cascade constraint;
DROP TABLE "MEMBER_TYPE";

-- 시퀀스 삭제
DROP SEQUENCE SEQ_MEMBER_ID;
DROP SEQUENCE SEQ_BOOK_ID;
DROP SEQUENCE SEQ_CHILD_ID;
DROP SEQUENCE SEQ_ORDER_ID;
DROP SEQUENCE SEQ_ADDRESS_ID;
DROP SEQUENCE SEQ_DELIVERY_ADDRESS_ID;
DROP SEQUENCE SEQ_CATEGORY_ID;
DROP SEQUENCE SEQ_AGE_RATING_ID;
DROP SEQUENCE SEQ_PAYMENT_ID;

purge recyclebin;

-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BOOK_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CHILD_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ORDER_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAYMENT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ADDRESS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DELIVERY_ADDRESS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATEGORY_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AGE_RATING_ID START WITH 1 INCREMENT BY 1 NOCACHE;

-- AGE_RATINGS (연령등급)
CREATE TABLE "AGE_RATINGS" (
    "AGE_RATING_ID" NUMBER(4)    NOT NULL,
    "RATING_NAME"   VARCHAR2(15) NOT NULL
);

ALTER TABLE "AGE_RATINGS" ADD CONSTRAINT "PK_AGE_RATINGS" PRIMARY KEY ("AGE_RATING_ID");
ALTER TABLE "AGE_RATINGS" ADD CONSTRAINT "UK_RATING_NAME" UNIQUE ("RATING_NAME");

-- CATEGORIES (카테고리)
CREATE TABLE "CATEGORIES" (
    "CATEGORY_ID"   NUMBER(4)    NOT NULL,
    "AGE_RATING_ID" NUMBER(4)    NOT NULL,
    "CATEGORY_NAME" VARCHAR2(30) NOT NULL
);

ALTER TABLE "CATEGORIES" ADD CONSTRAINT "PK_CATEGORIES" PRIMARY KEY ("CATEGORY_ID");
ALTER TABLE "CATEGORIES" ADD CONSTRAINT "UK_CATEGORY_NAME_AGE" UNIQUE ("CATEGORY_NAME", "AGE_RATING_ID");
ALTER TABLE "CATEGORIES" ADD CONSTRAINT "FK_AGE_RATINGS_TO_CATEGORIES" 
    FOREIGN KEY ("AGE_RATING_ID") REFERENCES "AGE_RATINGS" ("AGE_RATING_ID");

-- BOOKS (도서)
CREATE TABLE "BOOKS" (
    "BOOK_ID"          NUMBER(10)     NOT NULL,
    "ISBN"             VARCHAR2(15)   NOT NULL,
    "BOOK_NAME"        VARCHAR2(30)   NOT NULL,
    "PUBLICATION_DATE" DATE           NOT NULL,
    "PAGE"             NUMBER(4)      NOT NULL,
    "LIST_PRICE"       NUMBER(10)     NOT NULL,
    "SALE_PRICE"       NUMBER(10)     NOT NULL,
    "REWARD_POINT"     NUMBER(5)      NOT NULL,
    "TAX_DEDUCTION_YN" NUMBER(1)      NOT NULL,
    "PUBLISHER_NAME"   VARCHAR2(30)   NOT NULL,
    "AUTHER_NAME"      VARCHAR2(30)   NOT NULL,
    "BOOK_SIZE"        VARCHAR2(15)   NOT NULL,
    "IMAGE_URL"        VARCHAR2(4000) NULL,
    "CATEGORY_ID"      NUMBER(4)      NOT NULL
);

ALTER TABLE "BOOKS" ADD CONSTRAINT "PK_BOOKS" PRIMARY KEY ("BOOK_ID");
ALTER TABLE "BOOKS" ADD CONSTRAINT "UK_BOOKS_ISBN" UNIQUE ("ISBN");
ALTER TABLE "BOOKS" ADD CONSTRAINT "FK_CATEGORIES_TO_BOOKS" 
    FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORIES" ("CATEGORY_ID");
ALTER TABLE "BOOKS" ADD CONSTRAINT "CK_TAX_DEDUCTION_YN" CHECK (TAX_DEDUCTION_YN IN (0, 1));

-- MEMBER (회원)
CREATE TABLE "MEMBER" (
    "MEMBER_ID"       NUMBER(10)   NOT NULL,
    "MEMBER_LOGIN_ID" VARCHAR2(15) NOT NULL,
    "PASSWORD"        VARCHAR2(20) NOT NULL,
    "MEMBER_NAME"     VARCHAR2(20) NOT NULL,
    "SEX"             NUMBER(1)    NOT NULL,
    "PHONE_NUMBER"    VARCHAR2(20) NOT NULL,
    "BIRTH_DATE"      DATE         NOT NULL,
    "EMAIL"           VARCHAR2(30) NOT NULL,
    "HAS_CHILDREN"    NUMBER(1)    NOT NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_ID");
ALTER TABLE "MEMBER" ADD CONSTRAINT "UK_MEMBER_LOGIN_ID" UNIQUE ("MEMBER_LOGIN_ID");
ALTER TABLE "MEMBER" ADD CONSTRAINT "UK_MEMBER_PHONE" UNIQUE ("PHONE_NUMBER");
ALTER TABLE "MEMBER" ADD CONSTRAINT "UK_MEMBER_EMAIL" UNIQUE ("EMAIL");
ALTER TABLE "MEMBER" ADD CONSTRAINT "CK_MEMBER_SEX" CHECK (SEX IN (0, 1));
ALTER TABLE "MEMBER" ADD CONSTRAINT "CK_HAS_CHILDREN" CHECK (HAS_CHILDREN IN (0, 1));

-- MEMBER_TYPE (회원 종류)
CREATE TABLE "MEMBER_TYPE" (
    "MEMBER_ID"        NUMBER(10)  NOT NULL,
    "MEMBER_TYPE_CODE" VARCHAR2(20) NOT NULL
);

ALTER TABLE "MEMBER_TYPE" ADD CONSTRAINT "PK_MEMBER_TYPE" PRIMARY KEY ("MEMBER_ID");
ALTER TABLE "MEMBER_TYPE" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_TYPE" 
    FOREIGN KEY ("MEMBER_ID") REFERENCES "MEMBER" ("MEMBER_ID");
ALTER TABLE "MEMBER_TYPE" ADD CONSTRAINT "CK_MEMBER_TYPE_CODE" 
    CHECK (MEMBER_TYPE_CODE IN ('학부모', '학생', '학원강사', '학교선생님', '일반'));

-- ADDRESSES (주소)
CREATE TABLE "ADDRESSES" (
    "ADDRESS_ID"     NUMBER(4)     NOT NULL,
    "POSTAL_CODE"    VARCHAR2(10)  NOT NULL,
    "BASE_ADDRESS"   VARCHAR2(100) NOT NULL,
    "DETAIL_ADDRESS" VARCHAR2(100) NOT NULL,
    "MEMBER_ID"      NUMBER(10)    NOT NULL
);

ALTER TABLE "ADDRESSES" ADD CONSTRAINT "PK_ADDRESSES" PRIMARY KEY ("ADDRESS_ID");
ALTER TABLE "ADDRESSES" ADD CONSTRAINT "FK_MEMBER_TO_ADDRESSES" 
    FOREIGN KEY ("MEMBER_ID") REFERENCES "MEMBER" ("MEMBER_ID");

-- DELIVERY_ADDRESSES (배송정보)
CREATE TABLE "DELIVERY_ADDRESSES" (
    "DELIVERY_ADDRESS_ID" NUMBER(4)     NOT NULL,
    "POSTAL_CODE"         VARCHAR2(10)  NOT NULL,
    "BASE_ADDRESS"        VARCHAR2(100) NOT NULL,
    "DETAIL_ADDRESS"      VARCHAR2(100) NOT NULL,
    "DELIVERY_REQUEST"    VARCHAR2(100) NOT NULL,
    "MOBILE_NUMBER"       VARCHAR2(15)  NOT NULL,
    "PHONE_NUMBER"        VARCHAR2(15)  NULL,
    "MEMBER_ID"           NUMBER(10)    NOT NULL
);

ALTER TABLE "DELIVERY_ADDRESSES" ADD CONSTRAINT "PK_DELIVERY_ADDRESSES" PRIMARY KEY ("DELIVERY_ADDRESS_ID");
ALTER TABLE "DELIVERY_ADDRESSES" ADD CONSTRAINT "FK_MEMBER_TO_DELIVERY_ADDRESSES" 
    FOREIGN KEY ("MEMBER_ID") REFERENCES "MEMBER" ("MEMBER_ID");

-- CHILDREN (자녀)
CREATE TABLE "CHILDREN" (
    "CHILD_ID"   NUMBER(4)  NOT NULL,
    "MEMBER_ID"  NUMBER(10) NOT NULL,
    "BIRTH_DATE" DATE       NOT NULL
);

ALTER TABLE "CHILDREN" ADD CONSTRAINT "PK_CHILDREN" PRIMARY KEY ("CHILD_ID");
ALTER TABLE "CHILDREN" ADD CONSTRAINT "FK_MEMBER_TO_CHILDREN" 
    FOREIGN KEY ("MEMBER_ID") REFERENCES "MEMBER" ("MEMBER_ID");

-- ORDERS (주문)
CREATE TABLE "ORDERS" (
    "ORDER_ID"            NUMBER(4)  NOT NULL,
    "BOOK_ID"             NUMBER(10) NOT NULL,
    "MEMBER_ID"           NUMBER(10) NOT NULL,
    "DELIVERY_ADDRESS_ID" NUMBER(4)  NOT NULL,
    "DELIVERY_FEE"        NUMBER(4)  NOT NULL,
    "QUANTITY"            NUMBER(3)  NOT NULL,
    "PAYMENT_AMOUNT"      NUMBER(10) NOT NULL
);

ALTER TABLE "ORDERS" ADD CONSTRAINT "PK_ORDERS" PRIMARY KEY ("ORDER_ID");
ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_BOOKS_TO_ORDERS" 
    FOREIGN KEY ("BOOK_ID") REFERENCES "BOOKS" ("BOOK_ID");
ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_MEMBER_TO_ORDERS" 
    FOREIGN KEY ("MEMBER_ID") REFERENCES "MEMBER" ("MEMBER_ID");
ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_DELIVERY_ADDRESSES_TO_ORDERS" 
    FOREIGN KEY ("DELIVERY_ADDRESS_ID") REFERENCES "DELIVERY_ADDRESSES" ("DELIVERY_ADDRESS_ID");

-- PAYMENT_METHODS (결제수단)
CREATE TABLE PAYMENT_METHODS (
    PAYMENT_ID NUMBER(4) NOT NULL,
    ORDER_ID NUMBER(4) NOT NULL,
    PAYMENT_TYPE VARCHAR2(20) NOT NULL
);

ALTER TABLE PAYMENT_METHODS ADD CONSTRAINT PK_PAYMENT_METHODS PRIMARY KEY (PAYMENT_ID);
ALTER TABLE "PAYMENT_METHODS" ADD CONSTRAINT "UK_ORDER_PAYMENT" UNIQUE ("ORDER_ID");
ALTER TABLE "PAYMENT_METHODS" ADD CONSTRAINT "FK_ORDERS_TO_PAYMENT_METHODS" 
    FOREIGN KEY ("ORDER_ID") REFERENCES "ORDERS" ("ORDER_ID");

-- CART_ITEMS (장바구니)
CREATE TABLE "CART_ITEMS" (
    "MEMBER_ID" NUMBER(10)   NOT NULL,
    "BOOK_ID"   NUMBER(10)   NOT NULL,
    "QUANTITY"  NUMBER(3)    NOT NULL,
    "BOOK_NAME" VARCHAR2(30) NOT NULL,
    "PRICE"     NUMBER(10)   NOT NULL
);

ALTER TABLE "CART_ITEMS" ADD CONSTRAINT "PK_CART_ITEMS" PRIMARY KEY ("MEMBER_ID", "BOOK_ID");
ALTER TABLE "CART_ITEMS" ADD CONSTRAINT "FK_MEMBER_TO_CART_ITEMS" 
    FOREIGN KEY ("MEMBER_ID") REFERENCES "MEMBER" ("MEMBER_ID");
ALTER TABLE "CART_ITEMS" ADD CONSTRAINT "FK_BOOKS_TO_CART_ITEMS" 
    FOREIGN KEY ("BOOK_ID") REFERENCES "BOOKS" ("BOOK_ID");


