insert문 수정
-- AGE_RATINGS (연령등급) 데이터
INSERT INTO AGE_RATINGS (RATING_NAME) VALUES ('영유아');
INSERT INTO AGE_RATINGS (RATING_NAME) VALUES ('초등');
INSERT INTO AGE_RATINGS (RATING_NAME) VALUES ('중등');
INSERT INTO AGE_RATINGS (RATING_NAME) VALUES ('고등');
INSERT INTO AGE_RATINGS (RATING_NAME) VALUES ('교과서');

-- CATEGORIES (카테고리) 데이터
-- 영유아 카테고리 
INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '영유아도서'
FROM AGE_RATINGS 
WHERE RATING_NAME = '영유아';

-- 초등 카테고리
INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '전과목교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '초등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '수학교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '초등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '영어교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '초등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '한자교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '초등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '시험대비교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '초등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '월간지'
FROM AGE_RATINGS 
WHERE RATING_NAME = '초등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '예비중학생'
FROM AGE_RATINGS 
WHERE RATING_NAME = '초등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '학습만화'
FROM AGE_RATINGS 
WHERE RATING_NAME = '초등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '기타'
FROM AGE_RATINGS 
WHERE RATING_NAME = '초등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '아동도서'
FROM AGE_RATINGS 
WHERE RATING_NAME = '초등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '학습지'
FROM AGE_RATINGS 
WHERE RATING_NAME = '초등';

-- 중등 카테고리
INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '전과목교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '중등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '국어교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '중등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '영어교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '중등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '수학교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '중등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '사회교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '중등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '과학교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '중등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '시험대비교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '중등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '밀크T교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '중등';

-- 고등 카테고리
INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '전과목교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '고등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '국어교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '고등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '영어교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '고등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '수학교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '고등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '사회교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '고등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '과학교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '고등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '시험대비교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '고등';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '밀크T교재'
FROM AGE_RATINGS 
WHERE RATING_NAME = '고등';

-- 교과서 카테고리
INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '초등'
FROM AGE_RATINGS 
WHERE RATING_NAME = '교과서';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '중등'
FROM AGE_RATINGS 
WHERE RATING_NAME = '교과서';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '고등'
FROM AGE_RATINGS 
WHERE RATING_NAME = '교과서';

INSERT INTO CATEGORIES (AGE_RATING_ID, CATEGORY_NAME) 
SELECT AGE_RATING_ID, '교과서판매처'
FROM AGE_RATINGS 
WHERE RATING_NAME = '교과서';

-- BOOKS 데이터
INSERT INTO BOOKS (ISBN, BOOK_NAME, PUBLICATION_DATE, PAGE, LIST_PRICE, SALE_PRICE, REWARD_POINT, 
                  TAX_DEDUCTION_YN, PUBLISHER_NAME, AUTHER_NAME, BOOK_SIZE, IMAGE_URL, CATEGORY_ID)
SELECT '9788912345671', '초등 수학 기본서', TO_DATE('2024-01-10', 'YYYY-MM-DD'), 200, 25000, 22500, 225, 1, 
       '천재교육', '강수학', 'B5', NULL, CATEGORY_ID
FROM CATEGORIES 
WHERE CATEGORY_NAME = '수학교재' 
AND AGE_RATING_ID = (SELECT AGE_RATING_ID FROM AGE_RATINGS WHERE RATING_NAME = '초등');

INSERT INTO BOOKS (ISBN, BOOK_NAME, PUBLICATION_DATE, PAGE, LIST_PRICE, SALE_PRICE, REWARD_POINT, 
                  TAX_DEDUCTION_YN, PUBLISHER_NAME, AUTHER_NAME, BOOK_SIZE, IMAGE_URL, CATEGORY_ID)
SELECT '9788912345672', '중학 영어 기본서', TO_DATE('2024-01-15', 'YYYY-MM-DD'), 250, 28000, 25200, 252, 1, 
       '천재교육', '이영어', 'A4', NULL, CATEGORY_ID
FROM CATEGORIES 
WHERE CATEGORY_NAME = '영어교재' 
AND AGE_RATING_ID = (SELECT AGE_RATING_ID FROM AGE_RATINGS WHERE RATING_NAME = '중등');

INSERT INTO BOOKS (ISBN, BOOK_NAME, PUBLICATION_DATE, PAGE, LIST_PRICE, SALE_PRICE, REWARD_POINT, 
                  TAX_DEDUCTION_YN, PUBLISHER_NAME, AUTHER_NAME, BOOK_SIZE, IMAGE_URL, CATEGORY_ID)
SELECT '9788912345673', '고등 국어 기본서', TO_DATE('2024-01-20', 'YYYY-MM-DD'), 300, 32000, 28800, 288, 1, 
       '천재교육', '박국어', 'A4', NULL, CATEGORY_ID
FROM CATEGORIES 
WHERE CATEGORY_NAME = '국어교재' 
AND AGE_RATING_ID = (SELECT AGE_RATING_ID FROM AGE_RATINGS WHERE RATING_NAME = '고등');

INSERT INTO BOOKS (ISBN, BOOK_NAME, PUBLICATION_DATE, PAGE, LIST_PRICE, SALE_PRICE, REWARD_POINT, 
                  TAX_DEDUCTION_YN, PUBLISHER_NAME, AUTHER_NAME, BOOK_SIZE, IMAGE_URL, CATEGORY_ID)
SELECT '9788912345674', '중학 과학 기본서', TO_DATE('2024-01-25', 'YYYY-MM-DD'), 180, 23000, 20700, 207, 1, 
       '천재교육', '최과학', 'B5', NULL, CATEGORY_ID
FROM CATEGORIES 
WHERE CATEGORY_NAME = '과학교재' 
AND AGE_RATING_ID = (SELECT AGE_RATING_ID FROM AGE_RATINGS WHERE RATING_NAME = '중등');

INSERT INTO BOOKS (ISBN, BOOK_NAME, PUBLICATION_DATE, PAGE, LIST_PRICE, SALE_PRICE, REWARD_POINT, 
                  TAX_DEDUCTION_YN, PUBLISHER_NAME, AUTHER_NAME, BOOK_SIZE, IMAGE_URL, CATEGORY_ID)
SELECT '9788912345675', '영유아 학습선물세트', TO_DATE('2024-01-30', 'YYYY-MM-DD'), 30, 15000, 13500, 135, 1, 
       '천재교육', '정선생', 'B4', NULL, CATEGORY_ID
FROM CATEGORIES 
WHERE CATEGORY_NAME = '영유아도서' 
AND AGE_RATING_ID = (SELECT AGE_RATING_ID FROM AGE_RATINGS WHERE RATING_NAME = '영유아');

INSERT INTO BOOKS (ISBN, BOOK_NAME, PUBLICATION_DATE, PAGE, LIST_PRICE, SALE_PRICE, REWARD_POINT, 
                  TAX_DEDUCTION_YN, PUBLISHER_NAME, AUTHER_NAME, BOOK_SIZE, IMAGE_URL, CATEGORY_ID)
SELECT '9788912345676', '초등 과학 기본서', TO_DATE('2024-01-05', 'YYYY-MM-DD'), 220, 26000, 23400, 234, 1, 
       '천재교육', '김과학', 'B5', NULL, CATEGORY_ID
FROM CATEGORIES 
WHERE CATEGORY_NAME = '과학교재' 
AND AGE_RATING_ID = (SELECT AGE_RATING_ID FROM AGE_RATINGS WHERE RATING_NAME = '초등');

INSERT INTO BOOKS (...)
SELECT '9788912345677', '중학 수학 기본서', TO_DATE('2024-01-08', 'YYYY-MM-DD'), 280, 29000, 26100, 261, 1,
       '천재교육', '이수학', 'A4', NULL, CATEGORY_ID
FROM CATEGORIES 
WHERE CATEGORY_NAME = '수학교재' 
AND AGE_RATING_ID = (SELECT AGE_RATING_ID FROM AGE_RATINGS WHERE RATING_NAME = '중등');

-- MilkT 교재 추가
INSERT INTO BOOKS (...)
SELECT '9788912345678', '고등 MilkT 수학', TO_DATE('2024-02-01', 'YYYY-MM-DD'), 300, 35000, 31500, 315, 1,
       '천재교육', '밀크티수학연구소', 'A4', NULL, CATEGORY_ID
FROM CATEGORIES 
WHERE CATEGORY_NAME = '밀크T교재' 
AND AGE_RATING_ID = (SELECT AGE_RATING_ID FROM AGE_RATINGS WHERE RATING_NAME = '고등');

-- 학습만화 추가
INSERT INTO BOOKS (...)
SELECT '9788912345679', '재미있는 과학만화', TO_DATE('2024-01-20', 'YYYY-MM-DD'), 160, 15000, 13500, 135, 1,
       '천재교육', '만화과학팀', 'B5', NULL, CATEGORY_ID
FROM CATEGORIES 
WHERE CATEGORY_NAME = '학습만화' 
AND AGE_RATING_ID = (SELECT AGE_RATING_ID FROM AGE_RATINGS WHERE RATING_NAME = '초등');


-- MEMBER 데이터
INSERT INTO MEMBER (MEMBER_LOGIN_ID, PASSWORD, MEMBER_NAME, SEX, PHONE_NUMBER, BIRTH_DATE, EMAIL, HAS_CHILDREN)
VALUES ('parent1', 'pass123', '김학부', 1, '010-1234-5678', TO_DATE('1985-03-15', 'YYYY-MM-DD'), 'parent1@email.com', 1);

INSERT INTO MEMBER (MEMBER_LOGIN_ID, PASSWORD, MEMBER_NAME, SEX, PHONE_NUMBER, BIRTH_DATE, EMAIL, HAS_CHILDREN)
VALUES ('student1', 'pass456', '이학생', 0, '010-2345-6789', TO_DATE('2005-07-22', 'YYYY-MM-DD'), 'student1@email.com', 0);

INSERT INTO MEMBER (MEMBER_LOGIN_ID, PASSWORD, MEMBER_NAME, SEX, PHONE_NUMBER, BIRTH_DATE, EMAIL, HAS_CHILDREN)
VALUES ('teacher1', 'pass789', '박선생', 1, '010-3456-7890', TO_DATE('1982-11-30', 'YYYY-MM-DD'), 'teacher1@email.com', 0);

INSERT INTO MEMBER (MEMBER_LOGIN_ID, PASSWORD, MEMBER_NAME, SEX, PHONE_NUMBER, BIRTH_DATE, EMAIL, HAS_CHILDREN)
VALUES ('tutor1', 'pass234', '최강사', 0, '010-4567-8901', TO_DATE('1988-04-25', 'YYYY-MM-DD'), 'tutor1@email.com', 0);

INSERT INTO MEMBER (MEMBER_LOGIN_ID, PASSWORD, MEMBER_NAME, SEX, PHONE_NUMBER, BIRTH_DATE, EMAIL, HAS_CHILDREN)
VALUES ('normal1', 'pass567', '정일반', 0, '010-5678-9012', TO_DATE('1995-09-10', 'YYYY-MM-DD'), 'normal1@email.com', 0);

-- MEMBER_TYPE 데이터
INSERT INTO MEMBER_TYPE (MEMBER_ID, MEMBER_TYPE_CODE)
SELECT MEMBER_ID, '학부모'
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'parent1';

INSERT INTO MEMBER_TYPE (MEMBER_ID, MEMBER_TYPE_CODE)
SELECT MEMBER_ID, '학생'
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'student1';

INSERT INTO MEMBER_TYPE (MEMBER_ID, MEMBER_TYPE_CODE)
SELECT MEMBER_ID, '학교선생님'
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'teacher1';

INSERT INTO MEMBER_TYPE (MEMBER_ID, MEMBER_TYPE_CODE)
SELECT MEMBER_ID, '학원강사'
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'tutor1';

INSERT INTO MEMBER_TYPE (MEMBER_ID, MEMBER_TYPE_CODE)
SELECT MEMBER_ID, '일반'
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'normal1';

-- ADDRESSES 데이터
INSERT INTO ADDRESSES (POSTAL_CODE, BASE_ADDRESS, DETAIL_ADDRESS, MEMBER_ID)
SELECT '12345', '서울시 강남구', '역삼동 123-45', MEMBER_ID
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'parent1';

INSERT INTO ADDRESSES (POSTAL_CODE, BASE_ADDRESS, DETAIL_ADDRESS, MEMBER_ID)
SELECT '23456', '서울시 서초구', '서초동 234-56', MEMBER_ID
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'student1';

INSERT INTO ADDRESSES (POSTAL_CODE, BASE_ADDRESS, DETAIL_ADDRESS, MEMBER_ID)
SELECT '34567', '서울시 마포구', '합정동 345-67', MEMBER_ID
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'teacher1';

INSERT INTO ADDRESSES (POSTAL_CODE, BASE_ADDRESS, DETAIL_ADDRESS, MEMBER_ID)
SELECT '45678', '서울시 영등포구', '여의도동 456-78', MEMBER_ID
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'tutor1';

INSERT INTO ADDRESSES (POSTAL_CODE, BASE_ADDRESS, DETAIL_ADDRESS, MEMBER_ID)
SELECT '56789', '서울시 송파구', '잠실동 567-89', MEMBER_ID
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'normal1';

-- DELIVERY_ADDRESSES 데이터
INSERT INTO DELIVERY_ADDRESSES (POSTAL_CODE, BASE_ADDRESS, DETAIL_ADDRESS, DELIVERY_REQUEST, 
                              MOBILE_NUMBER, PHONE_NUMBER, MEMBER_ID)
SELECT '12345', '서울시 강남구', '역삼동 123-45', '문 앞에 놓아주세요', '010-1234-5678', NULL, MEMBER_ID
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'parent1';

INSERT INTO DELIVERY_ADDRESSES (POSTAL_CODE, BASE_ADDRESS, DETAIL_ADDRESS, DELIVERY_REQUEST, 
                              MOBILE_NUMBER, PHONE_NUMBER, MEMBER_ID)
SELECT '23456', '서울시 서초구', '서초동 234-56', '경비실에 맡겨주세요', '010-2345-6789', NULL, MEMBER_ID
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'student1';

INSERT INTO DELIVERY_ADDRESSES (POSTAL_CODE, BASE_ADDRESS, DETAIL_ADDRESS, DELIVERY_REQUEST, 
                              MOBILE_NUMBER, PHONE_NUMBER, MEMBER_ID)
SELECT '34567', '서울시 마포구', '합정동 345-67', '부재시 연락주세요', '010-3456-7890', '02-345-6789', MEMBER_ID
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'teacher1';

-- CHILDREN 데이터
INSERT INTO CHILDREN (MEMBER_ID, BIRTH_DATE)
SELECT MEMBER_ID, TO_DATE('2015-05-20', 'YYYY-MM-DD')
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'parent1';

INSERT INTO CHILDREN (MEMBER_ID, BIRTH_DATE)
SELECT MEMBER_ID, TO_DATE('2018-08-15', 'YYYY-MM-DD')
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'parent1';

INSERT INTO CHILDREN (MEMBER_ID, BIRTH_DATE)
SELECT MEMBER_ID, TO_DATE('2014-03-10', 'YYYY-MM-DD')
FROM MEMBER
WHERE MEMBER_LOGIN_ID = 'student1';

-- ORDERS 데이터
INSERT INTO ORDERS (BOOK_ID, MEMBER_ID, DELIVERY_ADDRESS_ID, DELIVERY_FEE, QUANTITY, PAYMENT_AMOUNT)
SELECT b.BOOK_ID, m.MEMBER_ID, da.DELIVERY_ADDRESS_ID, 2500, 1, 25000
FROM BOOKS b, MEMBER m, DELIVERY_ADDRESSES da
WHERE b.BOOK_NAME = '초등 수학 기본서'
AND m.MEMBER_LOGIN_ID = 'parent1'
AND da.MEMBER_ID = m.MEMBER_ID;

INSERT INTO ORDERS (BOOK_ID, MEMBER_ID, DELIVERY_ADDRESS_ID, DELIVERY_FEE, QUANTITY, PAYMENT_AMOUNT)
SELECT b.BOOK_ID, m.MEMBER_ID, da.DELIVERY_ADDRESS_ID, 2500, 2, 56000
FROM BOOKS b, MEMBER m, DELIVERY_ADDRESSES da
WHERE b.BOOK_NAME = '중학 영어 기본서'
AND m.MEMBER_LOGIN_ID = 'student1'
AND da.MEMBER_ID = m.MEMBER_ID;

INSERT INTO ORDERS (BOOK_ID, MEMBER_ID, DELIVERY_ADDRESS_ID, DELIVERY_FEE, QUANTITY, PAYMENT_AMOUNT)
SELECT b.BOOK_ID, m.MEMBER_ID, da.DELIVERY_ADDRESS_ID, 0, 1, 32000
FROM BOOKS b, MEMBER m, DELIVERY_ADDRESSES da
WHERE b.BOOK_NAME = '고등 국어 기본서'
AND m.MEMBER_LOGIN_ID = 'teacher1'
AND da.MEMBER_ID = m.MEMBER_ID;

INSERT INTO ORDERS (BOOK_ID, MEMBER_ID, DELIVERY_ADDRESS_ID, DELIVERY_FEE, QUANTITY, PAYMENT_AMOUNT)
SELECT b.BOOK_ID, m.MEMBER_ID, da.DELIVERY_ADDRESS_ID, 2500, 2, b.SALE_PRICE * 2
FROM BOOKS b, MEMBER m, DELIVERY_ADDRESSES da
WHERE b.BOOK_NAME = '초등 과학 기본서'
AND m.MEMBER_LOGIN_ID = 'parent1'
AND da.MEMBER_ID = m.MEMBER_ID;

INSERT INTO ORDERS (...)
SELECT b.BOOK_ID, m.MEMBER_ID, da.DELIVERY_ADDRESS_ID, 0, 1, b.SALE_PRICE
FROM BOOKS b, MEMBER m, DELIVERY_ADDRESSES da
WHERE b.BOOK_NAME = '고등 MilkT 수학'
AND m.MEMBER_LOGIN_ID = 'teacher1'
AND da.MEMBER_ID = m.MEMBER_ID;

-- PAYMENT_METHODS 데이터
INSERT INTO PAYMENT_METHODS (ORDER_ID, PAYMENT_TYPE)
VALUES (1, '신용카드');

INSERT INTO PAYMENT_METHODS (ORDER_ID, PAYMENT_TYPE)
VALUES (2, '무통장입금');

INSERT INTO PAYMENT_METHODS (ORDER_ID, PAYMENT_TYPE)
VALUES (3, '간편결제');

INSERT INTO PAYMENT_METHODS (ORDER_ID, PAYMENT_TYPE)
VALUES (4, '휴대폰결제');

INSERT INTO PAYMENT_METHODS (ORDER_ID, PAYMENT_TYPE)
VALUES (5, '간편결제');

-- CART_ITEMS 데이터
INSERT INTO CART_ITEMS (MEMBER_ID, BOOK_ID, QUANTITY, BOOK_NAME, PRICE)
SELECT m.MEMBER_ID, b.BOOK_ID, 1, b.BOOK_NAME, b.SALE_PRICE
FROM MEMBER m, BOOKS b
WHERE m.MEMBER_LOGIN_ID = 'parent1'
AND b.BOOK_NAME = '중학 영어 기본서';

INSERT INTO CART_ITEMS (MEMBER_ID, BOOK_ID, QUANTITY, BOOK_NAME, PRICE)
SELECT m.MEMBER_ID, b.BOOK_ID, 1, b.BOOK_NAME, b.SALE_PRICE
FROM MEMBER m, BOOKS b
WHERE m.MEMBER_LOGIN_ID = 'student1'
AND b.BOOK_NAME = '고등 국어 기본서';

INSERT INTO CART_ITEMS (MEMBER_ID, BOOK_ID, QUANTITY, BOOK_NAME, PRICE)
SELECT m.MEMBER_ID, b.BOOK_ID, 2, b.BOOK_NAME, b.SALE_PRICE
FROM MEMBER m, BOOKS b
WHERE m.MEMBER_LOGIN_ID = 'teacher1'
AND b.BOOK_NAME = '초등 수학 기본서';

INSERT INTO CART_ITEMS (MEMBER_ID, BOOK_ID, QUANTITY, BOOK_NAME, PRICE)
SELECT m.MEMBER_ID, b.BOOK_ID, 1, b.BOOK_NAME, b.SALE_PRICE
FROM MEMBER m, BOOKS b
WHERE m.MEMBER_LOGIN_ID = 'student1'
AND b.BOOK_NAME = '재미있는 과학만화';

INSERT INTO CART_ITEMS (...)
SELECT m.MEMBER_ID, b.BOOK_ID, 1, b.BOOK_NAME, b.SALE_PRICE
FROM MEMBER m, BOOKS b
WHERE m.MEMBER_LOGIN_ID = 'teacher1'
AND b.BOOK_NAME = '고등 MilkT 수학';

COMMIT;

